### ISSUE TITLE
Investigate tracking more advanced MPI routines

### ISSUE THREAD

**Issue by huttered40** [huttered40/critter#4]
Currently, we've been focusing on the 5 MPI routines used in `cacqr2`. The other routines (both those implemented in `critter` and those that have not been implemented yet) need to either be debugged or implemented.

Add benchmarks for:
- [x] MPI_Barrier
- [ ] MPI_Gather
- [ ] MPI_Gatherv
- [ ] MPI_Allgatherv
- [ ] MPI_Scatter
- [ ] MPI_Scatterv
- [ ] MPI_Reduce_scatter
- [ ] MPI_Alltoall
- [ ] MPI_Alltoallv
- [x] MPI_Send
- [x] MPI_Recv
- [x] MPI_Isend
- [x] MPI_Irecv
- [x] MPI_Sendrecv

Investigate possible errors in:
- [x] MPI_Barrier
- [x] MPI_Gather
- [x] MPI_Gatherv
- [x] MPI_Allgatherv
- [x] MPI_Scatter
- [x] MPI_Scatterv
- [ ] MPI_Reduce_scatter
- [x] MPI_Alltoall
- [x] MPI_Alltoallv
- [x] MPI_Send
- [x] MPI_Recv
- [x] MPI_Isend
- [x] MPI_Irecv
- [x] MPI_Sendrecv

Investigate possibility of tracking:
- [ ] MPI non-blocking collectives
- [ ] MPI one-sided routines
